### ISSUE TITLE
Remove Deprecated Interface Usage

### ISSUE THREAD

**Issue by nealstewart** [goinstant/user-list#6]
Audit the repo and dependencies and remove deprecated interfaces.

https://goinstant.com/blog/six-api-improvements-to-make-goinstant-easier-with-several-deprecations

**Comment by colinmacdonald** [comment]
- [ ] Room#on() now supports local event subscription
- [ ] Room#users() is now a Key
- [ ] Room#user() now takes a userId string and returns a Key
- [ ] Introducing Room#self()
- [ ] Platform has been renamed to Connection (remove references to "platform" in docs)
- [ ] Event listener subscriptions are now synchronous (remove optional error callback)

**Comment by colinmacdonald** [comment]
This is complete. https://github.com/goinstant/user-list/pull/11
